language: java
dist: trusty
jdk: openjdk17
#addons:
#  apt:
#    packages:
#      - oracle.java11-installer   # https://github.com/travis-ci/travis-ci/issues/3259

script:
  - mvn test -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end

deploy:
  provider: script
  script: "mvn --settings .travis.settings.xml -DskipTests=true -B clean deploy"
  skip_cleanup: true

env:
  global:
    - MAVEN_OPTS="-Xmx2g"

cache:
  directories:
  - $HOME/.m2
